version: "3"
services:
  spark-master:
    image: "spark-master:latest"
    ports:
      - "8080:8080"
    networks:
      - spark-net
    deploy:
      placement:
        constraints:
          - node.labels.role==manager
  spark-worker:
    image: "spark-worker:latest"
    ports:
      - "8081:8081"
    environment:
      - CORES=7
    deploy:
      placement:
        constraints:
          - node.labels.role==worker
      replicas: 3
    networks:
      - spark-net
networks:
  spark-net:
    driver: overlay
