version: "3"
services:
  spark-master:
    image: spark-master:latest
    hostname: boss
    ports:
      - "4040:4040"
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-net
    deploy:
      placement:
        constraints:
          - node.labels.role==manager
  spark-worker:
    image: spark-worker:latest
    depends_on:
      - spark-master
    ports:
    environment:
      - CORES=7
    deploy:
      placement:
        constraints:
          - node.labels.role==worker
      replicas: 3
    networks:
      - spark-net
  spark-submit:
    image: spark-submit:latest
    depends_on:
      - spark-master
    ports: 
    deploy:
    networks:
      - spark-net
networks:
  spark-net:


